### PR TITLE
[fog][WARNING] 'mime-types' missing, please install and try again.

### PR DESCRIPTION
**Pull request by mariozaizar**
Hi! I noticed `rake` is not working out-of the box, because 'mime-types' is missing:

```
$ rake
Run options: --seed 59638
# Running:
EE...E..[fog][WARNING] 'mime-types' missing, please install and try again.
rake aborted!
```

After adding it to the Gemspec, it works:
```
rake
Run options: --seed 16680
# Running:
...............................................................................................
Finished in 0.769818s, 123.4058 runs/s, 211.7384 assertions/s.
95 runs, 163 assertions, 0 failures, 0 errors, 0 skips
```

### CODE REVIEW

**Comment by mariozaizar** [comment]
Looks like this will work only for ruby 2+.
> Gem::InstallError: mime-types-data requires Ruby version >= 2.0.

**Comment by mariozaizar** [comment]
**UPDATE:** This is breaking because the `fog > v1.32.0` requires `mime-types-data` gem, and that one supports only ruby 2.0.x. https://github.com/mime-types/mime-types-data/blob/master/mime-types-data.gemspec#L19.

Since remote_files's gemspec required `~> 1.15` new clones will try to install latest version (1.37) which introduced the dependence of mime-types and mime-types-data gems. This is why, old builds with the same code were green (they were using old versions of fog gems)

I also noticed we were not specifying any ruby version, that's why I didn't noticed any failures around ruby 1.9.3 or jruby. I think we should list those "target" versions in the readme and provide with a default version (by .ruby-version) with the lowest supported version.

**Comment by ggrossman** [comment]
@mariozaizar I think we could safely drop support for 1.9.3 in this gem; we have dropped 1.9.3 support in a number of our other public gems such as https://github.com/zendesk/credit_card_sanitizer, https://github.com/zendesk/active_record_host_pool, https://github.com/zendesk/active_record_shards

**Comment by steved** [comment]
mime-types 2.99 supports ruby 1.9 still, this is probably that bundler bug that where it doesn't pick up the latest "supported" version of a gem.

**Comment by mariozaizar** [comment]
@steved I'm using 2.6.1 since that was the last "green" version we used before..
And because it supports ruby 1.9.x.
> mime-types 2.6 supports Ruby 1.9.2 or later. https://rubygems.org/gems/mime-types/versions/2.6.1
I couldn't find that note with 2.99 though: https://rubygems.org/gems/mime-types/versions/2.99

@ggrossman this PR was intended to fix the rake spec, do you think I should remove 1.9.x support and remove the two extra locked versions?

**Comment by steved** [comment]
It's in the right column

screen shot 2016-01-21 at 3 19 24 pm

**Comment by mariozaizar** [comment]
I must be blind. Thanks @steved

**Comment by mariozaizar** [comment]
Closing this since ruby 1.9.x support has been deprecated with v3.0.0 (https://github.com/zendesk/remote_files/commit/f8e7b90ed88989671b695d0fd09548ae687821d6)
And now master specs works out of the box: https://travis-ci.org/zendesk/remote_files/builds/104211735 Thanks!

**Pull request closed without merging**
