### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by ellimist**
### Description

I've added individual commits for each change.

1. Use `directory_name` instead of `directory.key` to avoid doing an unnecessary request when deleting a file
2. Set 0 retries as default for the connection options
4. What year is it?! 🦕 Switch the CI from Travis to Github Actions.

### CODE REVIEW

**Comment by grosser** [comment]
- gem repos usually should not have a .ruby-version since they are supposed to work on any ruby version -> change gemspec to say `  spec.required_ruby_version = '>= 2.5.0'
`
- GA should test against all supported ruby versions (ideally for now 2.5-27 ... can try 3.0/3.1 but I bet they crash) see https://github.com/grosser/parallel/blob/master/.github/workflows/actions.yml#L14-L15
- version bumps should happen on master branch
- why are retries being lowered ?

**Comment by grosser** [comment]
... can also merge as-is since it's a good step forward anyway 👍

**Comment by ellimist** [comment]
> * gem repos usually should not have a .ruby-version since they are supposed to work on any ruby version -> change gemspec to say ` spec.required_ruby_version = '>= 2.5.0'`
> * GA should test against all supported ruby versions (ideally for now 2.5-27 ... can try 3.0/3.1 but I bet they crash) see https://github.com/grosser/parallel/blob/master/.github/workflows/actions.yml#L14-L15
> * version bumps should happen on master branch
> * why are retries being lowered ?

Thanks for your review 🙏🏼  I've addressed your comments.

- Removed .ruby-version and added the required_ruby_version to the gemspec
- Changed GA to test against all the previously tested ruby versions
- Removed the version bump
- I set the default retries to 0, but clients still have the opportunity to override them. It's weird to have this hidden default of 4 and only find out about it when it's the worst.

**Review by zendesk-giuseppe — APPROVED** [review]
👍 🚀 🇮🇹

**Comment by ellimist** [comment]
The scope of this PR is creeping, so I'm splitting it into multiple smaller ones.

**Comment by ellimist** [comment]
Split the changes into #22 #23 and #24

**Pull request closed without merging**
